"""Add decision_maker column to Lead model

Revision ID: 5cdd78588bbb
Revises: 
Create Date: 2026-03-06 12:12:57.594465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdd78588bbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_maker', sa.String(length=50), server_default='Self', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('decision_maker')

    # ### end Alembic commands ###
